Fix relative path to EEE_plot
open-energy-transition/heat-demand-peaks pull request #13
Opened 2024-03-01 14:11 UTC by yerbol-akhmetov

Good day. Here, I propose to fix relative path to `EEE_plot.py` file.

2024-03-04 14:50 UTC, martacki requested changes

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +                     'residential urban decentral resistive heater']
missing quite a few...?

```suggestion
    rh_techs_elec = ['residential rural ground heat pump',
                     'residential rural resistive heater', 
                     'residential urban decentral air heat pump',
                     'residential urban decentral resistive heater',
                     'urban central resistive heater',
                     'urban central air heat pump',
                     'residential rural air heat pump']
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    rh_techs_consume = rh_techs_consume.groupby(level=0, axis=1).sum()
```suggestion
    rh_gas_consume.T.groupby(level=0).sum().T
```
`axis` is deprecated, pls use `.T`

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    ev_tech_consume = ev_tech_consume.groupby(level=0, axis=1).sum()
```suggestion
    ev_tech_consume = ev_tech_consume.T.groupby(level=0).sum().T
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    ev_tech_prosume = ev_tech_prosume.groupby(level=0, axis=1).sum()
```suggestion
    ev_tech_prosume = ev_tech_prosume.T.groupby(level=0).sum().T
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    rh_mCHP_prosume = rh_mCHP_prosume.groupby(level=0, axis=1).sum()
```suggestion
    rh_mCHP_prosume = rh_mCHP_prosume.T.groupby(level=0).sum().T
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    rh_mCHP_consume = rh_mCHP_consume.groupby(level=0, axis=1).sum()
```suggestion
    rh_mCHP_consume = rh_mCHP_consume.T.groupby(level=0).sum().T
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +        rh_gas_consume = rh_gas_consume.groupby(level=0, axis=1).sum()
```suggestion
        rh_gas_consume = rh_gas_consume.T.groupby(level=0).sum().T
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    total_elec_load = (lv_load + rh_techs_consume + ev_tech_consume + ev_tech_prosume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
What about `rh_mCHP_consume`?

```suggestion
    total_elec_load = (lv_load + rh_techs_consume + ev_tech_consume + ev_tech_prosume + rh_mCHP_consume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +        total_gas_load = (rh_mCHP_consume + rh_gas_consume).multiply(n.snapshot_weightings.stores, axis=0)
Probably prosumer part should be included here
```suggestion
        total_gas_load = (rh_mCHP_consume +  rh_mCHP_prosume + rh_gas_consume).multiply(n.snapshot_weightings.stores, axis=0)
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +        total_gas_load = rh_mCHP_consume.multiply(n.snapshot_weightings.stores, axis=0)
```suggestion
        total_gas_load = (rh_mCHP_consume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
```

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +    n = network.copy()
why copy?

2024-03-04 14:50 UTC, martacki commented on plots/electricity_bills.py
> +
```suggestion
```

2024-03-04 14:50 UTC, martacki commented on plots/Households.xlsx
can you upload as .csv, not .xlsx?

2024-03-04 15:29 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +        total_gas_load = rh_mCHP_consume.multiply(n.snapshot_weightings.stores, axis=0)
Here, `else` condition considers situations of `rigid` and `retro_tes` scenarios without gas boilers. There we only has mCHP consumpion.

2024-03-04 15:52 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +    n = network.copy()
Removed

2024-03-04 15:53 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +    prices = n.loads_t.p_set.multiply(n.snapshot_weightings.stores, axis=0).multiply(n.buses_t.marginal_price[load_cols]).sum()
Ok, I will plot only `n.buses_t.marginal_cost` for `low voltage` per country.

2024-03-04 15:55 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +    n = network.copy()
I have removed it

2024-03-04 17:35 UTC, yerbol-akhmetov commented on plots/Households.xlsx
I have updated excel to csv.

2024-03-05 13:40 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +                     'residential urban decentral resistive heater']
Residential rural air heat pump was missing previously, but it was added in recent updated I guess.

2024-03-05 14:54 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +    total_elec_load = (lv_load + rh_techs_consume + ev_tech_consume + ev_tech_prosume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
> In mCHP, we have gas as consumable in bus0, while electricity (bus1) and heat (bus2) as product. `rh_mCHP_consume` is considered in gas part, we only have prosume here in electricity.

2024-03-05 14:57 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +        total_gas_load = (rh_mCHP_consume + rh_gas_consume).multiply(n.snapshot_weightings.stores, axis=0)
> Probably prosumer part should be included here

The gas load will not have `rh_mCHP_prosume`, because `rh_mCHP_prosume` refers to electricity production in bus1. We will have only `rh_mCHP_consume` (refers to bus0 of link) in gas load.

2024-03-05 15:11 UTC, martacki commented on plots/electricity_bills.py
> +    total_elec_load = (lv_load + rh_techs_consume + ev_tech_consume + ev_tech_prosume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
I wonder why in urban central, bus1 is not the low voltage bus...

2024-03-06 13:41 UTC, yerbol-akhmetov commented on plots/electricity_bills.py
> +    total_elec_load = (lv_load + rh_techs_consume + ev_tech_consume + ev_tech_prosume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
> Agree, thanks for clarification!
> 
> I wonder why in urban central, bus1 is not the low voltage bus... I think this is an error in upstream pypsa-eur?

Do you mean `urban central solid biomass CHP`? For solid biomass micro CHPs in residential and services, bus1 is low_voltage. But for urban central we do not have mCHP, instead we have regular `solid biomass CHP` which is connected to grid (i.e. bus1 is AC bus).

2024-03-06 13:57 UTC, martacki commented on plots/electricity_bills.py
> +    total_elec_load = (lv_load + rh_techs_consume + ev_tech_consume + ev_tech_prosume + rh_mCHP_prosume).multiply(n.snapshot_weightings.stores, axis=0)
No I think I saw it for gas boilers, for example, or some of the heat pumps, but I don't remember

2024-03-06 17:50 UTC, martacki approved these changes
Good job! :tada:

2024-03-06 17:50 UTC, merged